language: node_js
before_install: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
env:
  global:
  - secure: Zn1W37pvvDWaJJFcAkjfFnyA0/WbfkAIAZJ9Eykz8tjRcB/C+R56+4rnOsSoUEe3jSYwYFFznykPoSB3nLeb3LLGbpWphqvioqt/w7jfdbsY026w01/mM6ZKYfwYtPw+cOHKSUCTMo0iVzxtbYGC2pyFWbsDbOBUbtetuRkpJEM=
  - secure: lEGtmaHSBbREEYrF4xnBSTA94cjI11313qef86E2HL2zenmP2nNigvRQ3Gn+SzQ2obfBp3k+pXfesqESR3k1JPfj5g7/1Feo6aP1W4pm4TkDpUIfo44KDqGU8+nE+K1VyqAurCTw1+kKVvAAturEVENwodXHkil20vDtTDOQW4Y=
